name: event_checkin_app
description: Professional event check-in application with QR scanning and printing capabilities
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # UI and Navigation
  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.0
  
  # State Management
  provider: ^6.1.1
  
  # QR Code Scanning
  mobile_scanner: ^3.5.6
  # permission_handler: ^11.0.1
  
  # HTTP and API
  http: ^1.1.0
  dio: ^5.3.2
  
  # Local Storage
  shared_preferences: ^2.2.2
  # sqflite: ^2.3.0
  
  # Printing
  pdf: ^3.8.4
  print_bluetooth_thermal: ^1.1.6
  esc_pos_utils_plus: ^2.0.4
  image: ^4.3.0
  
  # Utilities
  intl: ^0.18.1
  uuid: ^4.1.0
  # connectivity_plus: ^5.0.1
  
  # UI Components
  flutter_spinkit: ^5.2.0
  # fluttertoast: ^8.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true